name: Deploy index.html to EC2

on:
  push:
    branches:
      - main  # Branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/key
          chmod 600 ~/.ssh/key
          ssh-keyscan -H ${{ secrets.EC2_IP_ADDRESS }} >> ~/.ssh/known_hosts
          ls -la ~/.ssh  # Debugging: List files and permissions

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/key ubuntu@${{ secrets.EC2_IP_ADDRESS }} "echo 'SSH connection successful!'"
          # List the home directory for debugging
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/key ubuntu@${{ secrets.EC2_IP_ADDRESS }} "ls -la"

      - name: Copy index.html to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/key ./index.html ubuntu@${{ secrets.EC2_IP_ADDRESS }}:/tmp/index.html

      - name: Setup Apache2 and Deploy index.html on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/key ubuntu@${{ secrets.EC2_IP_ADDRESS }} << 'EOF'
            # Update package lists, install apache2 and unzip utility
            sudo apt update -y
            sudo apt install apache2 -y
            sudo apt install unzip -y

            # Create the directory for your website
            sudo mkdir -p /var/www/html

            # Set permissions for the web directory
            sudo chown -R www-data:www-data /var/www/html

            # Copy index.html to the web directory
            sudo cp /tmp/index.html /var/www/html/index.html

            # Restart apache2 to apply changes
            sudo systemctl restart apache2
          EOF
