name: Deploy index.html to EC2

on:
  push:
    branches:
      - main  # Branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Apache2 on EC2 and Deploy index.html
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP_ADDRESS }} << 'EOF'
            # Update package lists, install apache2 and unzip utility
            sudo apt update -y
            sudo apt install apache2 -y
            sudo apt install unzip -y

            # Create the directory for your website
            sudo mkdir -p /var/www/html

            # Set permissions for the web directory
            sudo chown -R www-data:www-data /var/www/html

            # Copy index.html to the web directory
            sudo cp /tmp/index.html /var/www/html/index.html

            # Restart apache2 to apply changes
            sudo systemctl restart apache2
          EOF

      - name: Copy index.html to EC2
        run: |
          scp -o StrictHostKeyChecking=no ./index.html ubuntu@${{ secrets.EC2_IP_ADDRESS }}:/tmp/index.html
